export const MAIN_STYLE = {
  BUTTON_DEFAULT_HEIGHT: 46,
  BUTTON_DEFAULT_RADIUS: 10,
  CONTAINER_GAP: 10,
  INPUT_DEFAULT_HEIGHT: 46,
  INPUT_DEFAULT_PADDING_TOP: 8,
  INPUT_DEFAULT_PADDING_BOTTOM: 8,
  INPUT_DEFAULT_PADDING_LEFT: 10,
  INPUT_DEFAULT_PADDING_RIGHT: 10,
  INPUT_DEFAULT_RADIUS: 10,
};
